#identify as github actions file
---

#name of github action
name: Checks

#specify trigger
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    #OS action is running on
    runs-on: ubuntu-20.04
    #different things that run for the job
    steps: 
    #name of step
     - name: Login to Docker Hub
       #allows use of premade action which allows login to docker
       uses: docker/login-action@v1
       #
       with: 
         #parameters for action
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Checkout
     #checks out code within github actions job allows for next step
       uses: actions/checkout@v2
     - name: Test
       run: docker-compose run --rm app sh -c "python manage.py test"
     - name: Lint
       run: docker-compose run --rm app sh -c "flake8"